### ISSUE TITLE
Too many concurrent API calls

### ISSUE THREAD

**Issue by jackrwoods** [OSU-Sustainability-Office/energy-dashboard#120]
Popular browsers (such as Firefox) place a limit on the total number of concurrent network requests ([source](https://developer.mozilla.org/en-US/docs/Tools/Network_Monitor/request_details) - Refer to the "Request Timing" section). Our current data layer implementation does not watch for "blocked" requests; in other words, if a request is blocked by the browser (due to exceeding the concurrent network request limit), the request is never restarted. This places the UI in a forever loading state where UI elements are waiting for data that will never come.

I *suspect* the fix will include modifying [data_store.js](https://github.com/OSU-Sustainability-Office/energy-dashboard/blob/master/src/store/data_layer/data_store.js#L123) to handle (restart) blocked requests.

**Comment by kristinaxlee** [comment]
tried checking out the issue with Jack 12/22, and things seemed to be working fine. Issue could not be duplicated.
