### ISSUE TITLE
Homepage does not acknowledge user log-in

### ISSUE THREAD

**Issue by jackrwoods** [OSU-Sustainability-Office/energy-dashboard#121]
If you log in to the Energy Dashboard via the [homepage](https://dashboard.sustainability.oregonstate.edu/#/), you will notice that the login button does not disappear, the navigation bar does not show that the user has logged in, and there is no indication that the login process worked.

This fix will include assessing the homepage Vue component, identifying bugs, and implementing multiple fixes.

**Comment by kristinaxlee** [comment]
CORS issue with logging in:
```Access to XMLHttpRequest at 'https://api.sustainability.oregonstate.edu/v2/auth/user' from origin 'https://dashboard.sustainability.oregonstate.edu' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.```

issue is present in all apps calling the login API

**Comment by kristinaxlee** [comment]
^ CORS issue fixed, check: https://github.com/OSU-Sustainability-Office/lambda-common-layer/commit/e021f1a2c1db515b2807c44fe96fe332447e90dc

**Comment by kristinaxlee** [comment]
sign in acknowledged and works properly
