### ISSUE TITLE
Add Historical Data to Dashboard

### ISSUE THREAD

**Issue by jackrwoods** [OSU-Sustainability-Office/energy-dashboard#124]
In February, Lety asked Brogan and I to migrate some historical data from LevitonBMO to our dashboard. AFAIK, the data is sitting on the hard drive of the office computer. This needs to be inserted into the RDS database in such a manner as to make it available via the Energy Dashboard.

I will pick up this task in early 2021. I left this project half-finished so I should be on the hook for this one.

**Comment by solderq35** [comment]
No idea what this is talking about and there's no way I can complete this task at this time.
