### ISSUE TITLE
Add Next/Previous Arrows to Graphs

### ISSUE THREAD

**Issue by jackrwoods** [OSU-Sustainability-Office/energy-dashboard#132]
When viewing a graph on the dashboard, users should be able to step forward/backward by clicking arrows on the left and right side of each graph.

Let's say a user is looking at a week of data. By clicking the right arrow, the graph should advance by one week (showing the next week's data). If a user clicks the back button, the opposite should occur (the graph should show the previous week's data).

**Comment by MilanDonhowe** [comment]
I'll take this one
