### ISSUE TITLE
Migrate from Travis CI to GitHub Actions

### ISSUE THREAD

**Issue by MilanDonhowe** [OSU-Sustainability-Office/energy-dashboard#198]
Travis CI no longer provides free service to OSS so we'll need to migrate to github actions for our automated deployments & tests.  We'll need to create four "workflows" under the `.github` directory:

- [ ] Workflow for deploying serverless API
- [ ] Workflow for deploying frontend to github pages
- [ ] Workflow for running unit tests on opened PRs
- [ ] Workflow for deploying test build

**Comment by solderq35** [comment]
Should be resolved here: https://github.com/OSU-Sustainability-Office/energy-dashboard/pull/204

I included unit tests in the workflow files for frontend deployment to github pages / s3 test build, so we have a total of 3 workflow files.
