### ISSUE TITLE
Add SEC solar panel geometry / Handle new Tesla Panels

### ISSUE THREAD

**Issue by MilanDonhowe** [OSU-Sustainability-Office/energy-dashboard#218]

**Comment by solderq35** [comment]
SEC solar panels need work on transitioning to bar chart system. Tesla has also deprecated the old solar panel endpoint, so may use iframes for the new endpoint.

See:
Iframes for tesla: https://github.com/OSU-Sustainability-Office/energy-dashboard/pull/224
SEC panels: https://github.com/OSU-Sustainability-Office/energy-dashboard/pull/220
