### ISSUE TITLE
Contact Email Update

### ISSUE THREAD

**Issue by solderq35** [OSU-Sustainability-Office/energy-dashboard#284]
Update email here (https://dashboard.sustainability.oregonstate.edu/#/contact) to link to https://fa.oregonstate.edu/contact
- Update contact page to also mention you need to click "sustainability office" from the "category" dropdown on the email form
- And also update email for OSU SO Github Org I guess: https://github.com/OSU-Sustainability-Office
- And update any other mentions of this email address

**Comment by s-egge** [comment]
I created a Pull Request [here](https://github.com/OSU-Sustainability-Office/energy-dashboard/pull/291) that fixes all mentions of the email on the Energy Dashboard. The OSU SO Github will still need to be changed, but I don't see the email in any other Github repos.

**Comment by solderq35** [comment]
I changed the email on the GitHub Org as well
