### ISSUE TITLE
AWS RDS (SQL database) Certificate Expires by August 22, 2024

### ISSUE THREAD

**Issue by solderq35** [OSU-Sustainability-Office/energy-dashboard#334]
**Cert Expires August 22, 2024**

## Warning
- AWS Health Dashboard > Scheduled Changes
![image](https://github.com/OSU-Sustainability-Office/energy-dashboard/assets/82061589/a89c24ab-5d12-4e3f-b6ab-b5605ba84837)

## Fix (maybe)
- AWS RDS home > select "energy dashboard" > Modify > Connectivity > Certificate Authority
  - Not sure this is the right menu though to edit it
  - See also (general docs): https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.SSL.html
- https://us-west-2.console.aws.amazon.com/rds/home?region=us-west-2#modify-instance:id=energy-dashboard

**Comment by s-egge** [comment]
This has been updated to a certificate that should auto-renew now according to the AWS documentation.
